# promtail/config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'instance'
      - source_labels: ['__meta_docker_image']
        target_label: 'image'
      - source_labels: ['__meta_docker_container_name']
        regex: '.*/(guestbook-app-1|guestbook-db-1)'
        action: keep
      - source_labels: ['__meta_docker_container_name']
        regex: '.*/guestbook-app-1'
        target_label: 'job'
        replacement: 'app_logs'
      - source_labels: ['__meta_docker_container_name']
        regex: '.*/guestbook-db-1'
        target_label: 'job'
        replacement: 'db_logs'